version: '2'
services:
 zookeeper:
   image: quay.io/debezium/zookeeper:1.9
   ports:
     - "2181:2181"
     - "2888:2888"
     - "3888:3888"
   environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
 kafka:
   image: quay.io/debezium/kafka:1.9
   ports:
     - "9092:9092"
     - "29092:29092"
   links:
     - zookeeper
   environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - ALLOW_PLAINTEXT_LISTENER=yes
     - ALLOW_ANONYMOUS_LOGIN=yes
